---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Unit Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.8"
